<a href="https://colab.research.google.com/github/swethareddythukkani/GitHubTest/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# get dimension
print(a.ndim)
print(b.ndim)


1
2


In [9]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [20]:
# get type
print(a.dtype)
print(b.dtype)

int16
float64


In [17]:
 # get size int 16 uses 2 bytes int 32 uses 4 bytes
 print(a.itemsize)
 print(b.itemsize)

2
8


In [18]:
 # get total size
print(a.size)
print(b.size)

3
6


In [19]:
# no.of bytes which is a.size*a.itemsize
print(a.nbytes)
print(b.nbytes)


6
48


**Accessing/Changing specific elements,rows,columns,etc**


In [21]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# get a specific element [r,c], indexing starts from 0
c[1,5]

13

In [24]:
# you can also use negative notation
c[1,-2]

13

In [25]:
#get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# get a specific column
c[:,2]

array([ 3, 10])

In [27]:
#getting a little more fancy[startindex:endindex:stepsize]
c[0,1:6:2]

array([2, 4, 6])

In [29]:
c[0,1:-1:2]

array([2, 4, 6])

In [30]:
c[1,5]=20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [31]:
c[:,2]=5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


**3D example
**

In [33]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
 # get specific element(work outside in)
 d[0,1,1]

4

In [39]:
 #replace
 d[:,1,:]=[[9,9],[8,8]]

In [40]:
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

initializing different types of arrays


In [43]:
# all 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [50]:
#any othr number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [51]:
 # random decimal numbers
 np.random.rand(4,2)

array([[0.23288169, 0.32216422],
       [0.63824902, 0.56018907],
       [0.19757945, 0.5529102 ],
       [0.73310817, 0.72492567]])

In [53]:
# random integer values 7 is a end value
np.random.randint(7,size=(3,3))

array([[0, 5, 1],
       [5, 6, 4],
       [1, 3, 6]])

In [54]:
# random integer values 4 is a start value ,7 is a end value
np.random.randint(4,7,size=(3,3))

array([[4, 6, 4],
       [5, 4, 5],
       [6, 6, 4]])

In [56]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
# here b points to a it didnt copy
a=np.array([1,2,3])
b=a
print(b)
b[0]=100
print(a)

[1 2 3]
[100   2   3]


In [62]:
# now it just copies a to b
a=np.array([1,2,3])
b=a.copy()
print(b)
b[0]=100
print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]


mathematic


In [63]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [64]:
a+2

array([3, 4, 5, 6])

In [67]:
print(a-2)
print(a*2)
print(a/2)


[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [68]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [69]:
a**2

array([ 1,  4,  9, 16])

In [70]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [71]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

linear algebra


In [74]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [76]:
c=np.identity(3)
np.linalg.det(c)

1.0

statistics


In [79]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.min(stats,axis=1)

array([1, 4])

In [81]:
np.max(stats)

6

In [82]:
np.sum(stats)

21

In [83]:
np.sum(stats,axis=0)

array([5, 7, 9])

Reorganizing arrays

In [84]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [85]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [86]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
#horizantal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])